# Generated by Django 5.1.4 on 2025-12-27 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when object was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when object was soft deleted', null=True)),
                ('year', models.IntegerField()),
                ('north_star', models.TextField(help_text='Vision statement for the year')),
                ('yearly_theme', models.CharField(help_text="e.g., 'Year of Scale'", max_length=200)),
                ('time_horizon', models.IntegerField(choices=[(1, '1 Year'), (3, '3 Years'), (5, '5 Years'), (10, '10 Years')], default=1, help_text='Strategic planning time horizon')),
                ('five_whys', models.JSONField(blank=True, default=list, help_text="Array of five 'why' statements for deeper understanding")),
                ('is_active', models.BooleanField(default=True, help_text='Active status')),
                ('visual_url', models.URLField(blank=True, help_text='Link to Unsplash or uploaded image', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('user', 'year')},
            },
        ),
    ]
