# Generated by Django 6.0 on 2025-12-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Deletion timestamp', null=True),
        ),
        migrations.AddField(
            model_name='vision',
            name='five_whys',
            field=models.JSONField(blank=True, default=list, help_text="Array of five 'why' statements for deeper understanding"),
        ),
        migrations.AddField(
            model_name='vision',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active status'),
        ),
        migrations.AddField(
            model_name='vision',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='vision',
            name='time_horizon',
            field=models.IntegerField(choices=[(1, '1 Year'), (3, '3 Years'), (5, '5 Years'), (10, '10 Years')], default=1, help_text='Strategic planning time horizon'),
        ),
        migrations.AddField(
            model_name='vision',
            name='visual_url',
            field=models.URLField(blank=True, help_text='Link to Unsplash or uploaded image', max_length=500),
        ),
    ]
