# Generated by Django 5.1.4 on 2025-12-27 13:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_vision_deleted_at_vision_five_whys_vision_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when object was created'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when object was soft deleted', null=True),
        ),
        migrations.AlterField(
            model_name='vision',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vision',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when object was last updated'),
        ),
    ]
