# Generated by Django 5.1.4 on 2025-12-27 18:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('mentor', 'Mentor'), ('partner', 'Partner'), ('supporter', 'Supporter'), ('advisor', 'Advisor'), ('other', 'Other')], max_length=50)),
                ('role_description', models.TextField(help_text='Specific role/contribution')),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('relationship_depth', models.IntegerField(choices=[(1, 'Acquaintance'), (2, 'Professional Contact'), (3, 'Regular Collaborator'), (4, 'Close Associate'), (5, 'Trusted Confidant')], default=2, help_text='Depth of relationship from 1 (acquaintance) to 5 (trusted confidant)')),
                ('last_contact_date', models.DateField(blank=True, help_text='Date of last contact', null=True)),
                ('frequency_days', models.IntegerField(default=30, help_text='Expected contact frequency in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['name'],
            },
        ),
    ]
