# Generated by Django 5.1.4 on 2025-12-27 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Deletion timestamp', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='frequency_days',
            field=models.IntegerField(default=30, help_text='Expected contact frequency in days', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='person',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='person',
            name='last_contact_date',
            field=models.DateField(blank=True, help_text='Date of last contact', null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='relationship_depth',
            field=models.IntegerField(choices=[(1, 'Acquaintance'), (2, 'Professional Contact'), (3, 'Regular Collaborator'), (4, 'Close Associate'), (5, 'Trusted Confidant')], default=2, help_text='Depth of relationship from 1 (acquaintance) to 5 (trusted confidant)'),
        ),
    ]
