# Generated by Django 5.1.4 on 2025-12-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Deletion timestamp', null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', help_text='System health based on execution frequency', max_length=20),
        ),
        migrations.AddField(
            model_name='system',
            name='input_definition',
            field=models.TextField(blank=True, help_text='What inputs are required for this system'),
        ),
        migrations.AddField(
            model_name='system',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='system',
            name='last_execution_date',
            field=models.DateField(blank=True, help_text='Date of last execution', null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='output_kpi_link',
            field=models.CharField(blank=True, help_text='Link to KPI that tracks output of this system', max_length=255),
        ),
        migrations.AlterField(
            model_name='system',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', help_text='Rhythm: How often this system is executed', max_length=100),
        ),
    ]
