# Generated by Django 5.1.4 on 2025-12-27 12:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        ('vision', '0002_vision_deleted_at_vision_five_whys_vision_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='confidence_level',
            field=models.IntegerField(default=3, help_text='Confidence level from 1 (low) to 5 (high)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='goal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Deletion timestamp', null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('stalled', 'Stalled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='vision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='vision.vision'),
        ),
    ]
