# Generated by Django 5.1.4 on 2025-12-28 12:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        ('vision', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['strategic_level', 'target_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='goal',
            name='parent_goal',
            field=models.ForeignKey(blank=True, help_text='Parent goal for cascading goals structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_goals', to='goals.goal'),
        ),
        migrations.AddField(
            model_name='goal',
            name='strategic_level',
            field=models.CharField(choices=[('high', 'High Level (Strategic)'), ('low', 'Low Level (Tactical)')], db_index=True, default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='weight',
            field=models.FloatField(default=1.0, help_text="Weight of this goal in parent's progress calculation (0-10)", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['strategic_level', 'status'], name='goals_goal_strateg_e77945_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'vision', 'strategic_level'], name='goals_goal_user_id_e522d5_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status', 'target_date'], name='goals_goal_user_id_fd1297_idx'),
        ),
    ]
