# Generated by Django 5.1.4 on 2025-12-27 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstacles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obstacle',
            name='mitigation',
        ),
        migrations.AddField(
            model_name='obstacle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Deletion timestamp', null=True),
        ),
        migrations.AddField(
            model_name='obstacle',
            name='is_blocking',
            field=models.BooleanField(default=False, help_text='Whether this obstacle is currently blocking goal/execution completion'),
        ),
        migrations.AddField(
            model_name='obstacle',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='obstacle',
            name='mitigation_plan',
            field=models.TextField(blank=True, help_text='Detailed strategy to mitigate or resolve this obstacle'),
        ),
        migrations.AddField(
            model_name='obstacle',
            name='severity_index',
            field=models.IntegerField(default=5, help_text='Numeric severity index from 1 (minimal) to 10 (catastrophic)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
