# Generated by Django 5.1.4 on 2025-12-27 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, help_text='Current value of the KPI', max_digits=10)),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Target value to achieve', max_digits=10)),
                ('unit', models.CharField(help_text="e.g., 'USD', '%', 'units'", max_length=50)),
                ('trend_data', models.JSONField(blank=True, default=list, help_text='Historical snapshots of KPI values [{date, value}, ...]')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='goals.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['goal', 'name'],
            },
        ),
    ]
