# Generated by Django 5.1.4 on 2025-12-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='actual_value',
        ),
        migrations.AddField(
            model_name='kpi',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current value of the KPI', max_digits=10),
        ),
        migrations.AddField(
            model_name='kpi',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Deletion timestamp', null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='trend_data',
            field=models.JSONField(blank=True, default=list, help_text='Historical snapshots of KPI values [{date, value}, ...]'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='target_value',
            field=models.DecimalField(decimal_places=2, help_text='Target value to achieve', max_digits=10),
        ),
    ]
