# Generated by Django 5.1.4 on 2025-12-28 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='KPI value at this point in time', max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this snapshot was recorded')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='kpis.kpi')),
            ],
            options={
                'verbose_name': 'KPI History',
                'verbose_name_plural': 'KPI Histories',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['kpi', '-recorded_at'], name='kpis_kpihis_kpi_id_32b3e6_idx')],
            },
        ),
    ]
