# Generated by Django 5.1.4 on 2025-12-27 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflection_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='quarterly', help_text='Type of reflection: weekly, monthly, or quarterly', max_length=20)),
                ('quarter', models.IntegerField(blank=True, choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], null=True)),
                ('year', models.IntegerField()),
                ('week_number', models.IntegerField(blank=True, help_text='Week number for weekly reflections', null=True)),
                ('month', models.IntegerField(blank=True, help_text='Month number for monthly reflections', null=True)),
                ('wins', models.TextField(help_text='What went well this period?')),
                ('challenges', models.TextField(help_text="What didn't go as planned?")),
                ('lessons_learned', models.TextField(help_text='Key takeaways and insights')),
                ('adjustments', models.TextField(help_text='Plan adjustments for next period')),
                ('gratitude_log', models.TextField(blank=True, help_text='What are you grateful for this period?')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked for editing to preserve historical integrity')),
                ('locked_at', models.DateTimeField(blank=True, help_text='Timestamp when reflection was locked', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Deletion timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-quarter', '-month', '-week_number'],
                'unique_together': {('user', 'quarter', 'year', 'reflection_type')},
            },
        ),
    ]
