# Generated by Django 5.1.4 on 2025-12-27 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quarterlyreflection',
            options={'ordering': ['-year', '-quarter', '-month', '-week_number']},
        ),
        migrations.AlterUniqueTogether(
            name='quarterlyreflection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quarterlyreflection',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Deletion timestamp', null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreflection',
            name='gratitude_log',
            field=models.TextField(blank=True, help_text='What are you grateful for this period?'),
        ),
        migrations.AddField(
            model_name='quarterlyreflection',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='quarterlyreflection',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked for editing to preserve historical integrity'),
        ),
        migrations.AddField(
            model_name='quarterlyreflection',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when reflection was locked', null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreflection',
            name='month',
            field=models.IntegerField(blank=True, help_text='Month number for monthly reflections', null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreflection',
            name='reflection_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='quarterly', help_text='Type of reflection: weekly, monthly, or quarterly', max_length=20),
        ),
        migrations.AddField(
            model_name='quarterlyreflection',
            name='week_number',
            field=models.IntegerField(blank=True, help_text='Week number for weekly reflections', null=True),
        ),
        migrations.AlterField(
            model_name='quarterlyreflection',
            name='adjustments',
            field=models.TextField(help_text='Plan adjustments for next period'),
        ),
        migrations.AlterField(
            model_name='quarterlyreflection',
            name='quarter',
            field=models.IntegerField(blank=True, choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], null=True),
        ),
        migrations.AlterField(
            model_name='quarterlyreflection',
            name='wins',
            field=models.TextField(help_text='What went well this period?'),
        ),
        migrations.AlterUniqueTogether(
            name='quarterlyreflection',
            unique_together={('user', 'quarter', 'year', 'reflection_type')},
        ),
    ]
